title: CHEN_yl
logo: /images/Tom_Portrait.jpg
location: Guangzhou,CHINA
#description:
#show_downloads:
theme: jekyll-theme-minimal

nav:
  - title: 首页
    url: /
  - title: 作品
    url: /projects/
  - title: 心得感想
    url: /notes/
